name: "webrtc"

# TODO: re-enable after including build steps from workspace-automation
on:
  workflow_dispatch:
# on:
#   pull_request:
#     paths:
#       # in plugins/[config stuff]
#       - "plugins/.clang-*"
#       - "plugins/CMakeLists.txt"
#       - "plugins/*.cmake"
#       - "plugins/*.h"
#       - "plugins/*.cpp"
#       - "plugins/*.cc"
#       - "plugins/*.c"
#       - "plugins/*.cc.in"
#       # plugin path
#       - "plugins/common/**"
#       - "plugins/webrtc/**"
#       # patches
#       - "patches/**/*.patch"
#       # workflow definition itself
#       - ".github/workflows/webrtc.yaml"
#       - ".github/workflows/_plugin_cpp-ci.yaml"
#       - ".github/actions/homescreen-build/**"
#   push:
#     branches:
#       - main

jobs:
  webrtc:
    uses: ./.github/workflows/_plugin_cpp-ci.yaml
    with:
      name: "webrtc"
      